driver: clocksource: Change 'hv_get_register' to 'hv_get_msr'
Error Logs:
drivers/clocksource/hyperv_timer.c: In function 'read_hv_clock_msr':
drivers/clocksource/hyperv_timer.c:394:16: error: implicit declaration of function 'hv_get_register'; did you mean 'nvmem_register'? [-Wimplicit-function-declaration]
  394 |         return hv_get_register(HV_MSR_TIME_REF_COUNT);
      |                ^~~~~~~~~~~~~~~
      |                nvmem_register
make[4]: *** [scripts/Makefile.build:244: drivers/clocksource/hyperv_timer.o] Error 1

 * In 0e3f7d120086c8b9d6e1ae0dd4917fc529daa1ca, 'hv_get_register' function changed to 'hv_get_msr'.
 * This commit fixes 3fc783860e0846efa2e116985767f053b059af69.

Signed-off-by: Yang Jeong Hun <onyxclover9931@gmail.com>