drivers: hv: dxgkrnl: Switch 'uuid_le_cmp' to 'guid_equal'
Error Logs:
drivers/hv/dxgkrnl/dxgmodule.c: In function ‘dxg_probe_vmbus’:
drivers/hv/dxgkrnl/dxgmodule.c:756:13: error: implicit declaration of function ‘uuid_le_cmp’ [-Werror=implicit-function-declaration]
  756 |         if (uuid_le_cmp(hdev->dev_type, dxg_vmbus_id_table[0].guid) == 0) {
      |             ^~~~~~~~~~~

 * In f5b3c34, 'uuid_le_cmp' moved tp mei_dev.h, So 'uuid_le_cmp' can't use anymore.
 * Switch to 'guid_equal' to work correctly.

Test: Build and OpenGL test
Signed-off-by: Yang Jeong Hun <onyxclover9931@gmail.com>